export const CARD_BG = [
  { id: 1, bgcolor: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)" },
  { id: 2, bgcolor: "linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)" },
  { id: 3, bgcolor: "linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 100%)" },
  { id: 4, bgcolor: "linear-gradient(135deg, #fdfbfb 0%, #ebedee 100%)" },
  { id: 5, bgcolor: "linear-gradient(135deg, #f6d365 0%, #fda085 100%)" },
  { id: 6, bgcolor: "linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%)" },
  { id: 7, bgcolor: "linear-gradient(135deg, #fccb90 0%, #d57eeb 100%)" },
  { id: 8, bgcolor: "linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)" },
  { id: 9, bgcolor: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)" },
  { id: 10, bgcolor: "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)" },
];

export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas — no more generic prep.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top — making your learning more organized.",
  },
  {
    id: "04",
    title: "Understand the 'Why' Behind Answers",
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "05",
    title: "Save, Organize, and Revisit",
    description:
      "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.",
  },
];
